INSERT INTO BOOKS(BOOK_ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_GENRE, DATE_COMPLETED, RATING)
    VALUES(0, 'War and Peace', 'Leo Tolstoy', 'Historical Fiction', DATE '2022-12-12', 4.5);

INSERT INTO GAMES(GAME_ID, GAME_TITLE, GAME_GENRE, DATE_COMPLETED, RATING)
    VALUES(0, 'World of Warcraft', 'MMORPG', DATE '2023-01-04', 4);

INSERT INTO MOVIES(MOVIE_ID, MOVIE_TITLE, MOVIE_GENRE, MOVIE_PRODUCER, MOVIE_DIRECTOR, RATING)
    VALUES(0, 'Super Troopers', 'Comedy', 'Jay Chandrasekhar', 'Jay Chandrasekhar', 4);

INSERT INTO MUSIC(MUSIC_ID, SONG_TITLE, ALBUM_TITLE, SONG_ARTIST, SONG_GENRE, RATING)
    VALUES(0, 'Piano Sonata 14', '', 'Ludwig van Beethoven', 'Classical', 5);